### ISSUE TITLE
Get id or ip of server

### ISSUE THREAD

**Issue by XdeadrushX** [MTRNord/nordlab-hackerspace-door#116]
Hello, I'm starting my project, based on some things of yours, since the network that I connect has 7 servers, I'm trying to catch the ip of the server to determine which one to send to the bot, because in the network that I connect has a protocol to determine what ip to send it to, is there any way to know this?

thank's in advance..

**Comment by MTRNord** [comment]
Well its not auto getting them currently and you propably shouldnt use this code. Its not usable at all which is why I am not activly maintain it.

The Freifunk IPs are currently all manually from https://github.com/MTRNord/freifunk-bot/blob/master/handlers/tmp/communities.json
